### PR TITLE
Remove unused `for_reference-greasemonkey_code.js`

### PR DESCRIPTION
**Pull request by theresnotime**
- Remove unused `build/for_reference-greasemonkey_code.js`
- Update package-lock to new version

Bug: [T317762](https://phabricator.wikimedia.org/T317762)

### CODE REVIEW

**Comment by theresnotime** [comment]
(CI failure seems unrelated?)

**Comment by MusikAnimal** [comment]
Are you using Node 12.20.0 (as specified by the .nvmrc file)? There shouldn't be any changes to package-lock.json. If you don't already have it, I suggest installing [nvm](https://github.com/nvm-sh/nvm) to manage Node versions.

**Comment by theresnotime** [comment]
> Are you using Node 12.20.0 (as specified by the .nvmrc file)? There shouldn't be any changes to package-lock.json. If you don't already have it, I suggest installing [nvm](https://github.com/nvm-sh/nvm) to manage Node versions.

I use nvm - is it meant to automagically select the correct version from the `.nvmrc` file or do I need to tell it to...?

(clearly _not_, I'll fix this a sec..)

**Comment by MusikAnimal** [comment]
You know, sometimes it automagically changes for me, sometimes it doesn't... I'm not sure how it works! I manually ran `nvm use 12.20.0`.

**Comment by sbassett29** [comment]
LGTM, thanks for addressing.

**Pull request merged**
